_wandb:
    value:
        cli_version: 0.19.6
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": validation_mle_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": validation_overall_score
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": training_mle_loss_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": training_mle_score_mean_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 95
                - 103
            "2":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 95
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.11
            "5": 0.19.6
            "6": 4.48.2
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 1
data_dir:
    value: /data/agirard/Projects/TimeTravel-DifferentiableMetrics/data/transformed
dataset_type:
    value: TimeTravel
dev_file:
    value: dev_data_sample.json
file_label:
    value: _mle
learning_rate:
    value: 2e-05
logs_dir:
    value: /data/agirard/Projects/TimeTravel-DifferentiableMetrics/logs
max_gen_length:
    value: 250
max_length:
    value: 512
mle_checkpoint_path:
    value: /data/agirard/Projects/TimeTravel-DifferentiableMetrics/models/mle_2025-02-19-13/mle_checkpoint_epoch-epoch=01-step-step=000003-val_loss=validation_mle_loss=2.39.ckpt
mle_enabled:
    value: true
mle_epochs:
    value: 2
mle_from_checkpoint:
    value: true
model_dir:
    value: /data/agirard/Projects/TimeTravel-DifferentiableMetrics/models/mle_2025-02-20-09
model_name:
    value: facebook/bart-large-cnn
models_dir:
    value: /data/agirard/Projects/TimeTravel-DifferentiableMetrics/models
num_workers:
    value: 3
output_attentions:
    value: true
results_dir:
    value: /data/agirard/Projects/TimeTravel-DifferentiableMetrics/results
reward_metric:
    value: bart
root_dir:
    value: /data/agirard/Projects/TimeTravel-DifferentiableMetrics
shuffle:
    value: true
test_file:
    value: test_data_sample.json
train_file:
    value: train_supervised_small_sample.json
use_bart:
    value: true
use_custom_loss:
    value: false
