_wandb:
    value:
        cli_version: 0.19.6
        m:
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": bart_prediction_cf_avg_score
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": bart_edited_ending_initial_avg_score
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": bart_edited_ending_original_avg_score
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": bart_prediction_edited_avg_score
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": bart_edited_ending_cf_avg_score
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": validation_dto_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": training_dto_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": bart_prediction_initial_avg_score
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": bart_prediction_original_avg_score
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 95
                - 103
            "2":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 95
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.11
            "5": 0.19.6
            "6": 4.48.2
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
file_label:
    value: _dto
model_dir:
    value: /data/agirard/Projects/TimeTravel-DifferentiableMetrics/models/dto_2025-02-19-16
model_name:
    value: facebook/bart-large-cnn
